version: "3.8"
services:
  db:
    container_name: pg_db
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=angryasfuckgetoutofmymind
      - POSTGRES_USER=postgres
